/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1c1a",
        "outline": "#737972",
        "surface-bright": "#fbf9f5",
        "outline-variant": "#c2c8c0",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#424842",
        "on-surface": "#1b1c1a",
        "on-tertiary-fixed": "#2f1400",
        "primary-fixed": "#cceace",
        "surface-container-highest": "#e4e2de",
        "on-secondary-container": "#6b5f7b",
        "tertiary-fixed": "#ffdcc4",
        "error-container": "#ffdad6",
        "surface-container-low": "#f5f3ef",
        "on-primary-container": "#233d29",
        "tertiary-container": "#dd8f50",
        "secondary": "#655974",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#b0ceb2",
        "on-primary-fixed": "#07200f",
        "on-secondary-fixed": "#21172e",
        "secondary-fixed-dim": "#d0c1e0",
        "primary-container": "#8ba88e",
        "surface-container": "#efeeea",
        "on-tertiary-container": "#592c00",
        "tertiary": "#8e4e14",
        "surface-container-high": "#eae8e4",
        "background": "#fbf9f5",
        "primary": "#4a654e",
        "on-primary": "#ffffff",
        "secondary-container": "#ecdcfd",
        "on-tertiary-fixed-variant": "#6f3800",
        "surface": "#fbf9f5",
        "primary-fixed-dim": "#b0ceb2",
        "tertiary-fixed-dim": "#ffb780",
        "secondary-fixed": "#ecdcfd",
        "on-primary-fixed-variant": "#334d38",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#4d425c",
        "surface-tint": "#4a654e",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f2f0ed",
        "surface-dim": "#dbdad6",
        "surface-variant": "#e4e2de",
        "on-secondary": "#ffffff",
        "inverse-surface": "#30312e",
        "coral": "#F4A261",
        "coral-dark": "#e76f51",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "unit": "8px",
        "section-padding-mobile": "40px",
        "container-max": "1120px",
        "section-padding-desktop": "80px"
      },
      fontFamily: {
        "headline-xl": ["Nunito Sans"],
        "headline-md": ["Nunito Sans"],
        "body-md": ["Work Sans"],
        "headline-lg": ["Nunito Sans"],
        "body-lg": ["Work Sans"],
        "crisis-link": ["Nunito Sans"],
        "label-md": ["Work Sans"],
        "headline-xl-mobile": ["Nunito Sans"],
        "headline": ["Nunito Sans"],
        "body": ["Work Sans"],
      },
      fontSize: {
        "headline-xl": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "crisis-link": ["16px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "800" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-xl-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
